daemon=300                          # Check every 300s (5 minutes)
syslog=yes                          # To log
pid=/var/run/ddclient.pid
ssl=yes                             

# This is the configuration to use for Infomaniak DynDNS service : 
# It was copied from the official docs : https://www.infomaniak.com/fr/support/faq/40/utiliser-dyndns-infomaniak-et-ddclient-linux
protocol=dyndns2
ssl=yes
use=web
server=infomaniak.com
login=enter_your_login
password=enter_your_password
yourdomain.xyz